# Generated by Django 3.2.4 on 2024-07-28 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_excerpt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='author',
            new_name='owner',
        ),
    ]
