# Generated by Django 3.2.4 on 2024-07-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_author_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TO-DO', 'To do'), ('IN-PROGRESS', 'In progress'), ('DONE', 'Done')], default='TO-DO', max_length=255),
        ),
    ]
